Prepare supporting TYPO3 v13
helhum/typo3-config-handling pull request #55
Opened 2024-10-20 12:53 UTC by christophlehmann

* [ ] Require new helhum/typo3-console with support for v13

2024-12-05 15:45 UTC, helhum commented
Thanks @christophlehmann looks good so far. Do you want to continue with this one?

2025-04-17 11:19 UTC, christophlehmann commented
Hey @helhum, merge? :-)

2025-04-23 14:15 UTC, helhum reviewed
looks like minimal changes are required. I only have one question

2025-04-23 14:15 UTC, helhum commented on composer.json
> +        "helhum/typo3-console": "^8.1.1 || ^8.2.1",
this should not be necessary. why do you think it is?

2025-04-23 14:21 UTC, helhum requested changes
The mentioned change is required for typo3 12 to remain supported

2025-04-23 14:33 UTC, helhum commented on composer.json
> +        "helhum/typo3-console": "^8.1.1 || ^8.2.1",
done

2025-04-23 14:39 UTC, helhum approved these changes
Fixed the comments myself. Thanks for beginning this in the first place

2025-04-23 14:41 UTC, merged

2025-04-23 15:07 UTC, helhum commented
Thanks @christophlehmann !